# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Back_End',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/Back_End',
                'lib_path': 'Back_End'},
  'syms': {}}
